language: php

php:
  - 7.3
  - 7.4
  - 8.0

services:
  - mysql

before_script:
  - cp .env.example .env
  - mysql -u root -e 'create database laravel;'
  - composer self-update --2
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - php artisan migrate
  - php artisan db:seed
